### ISSUE TITLE
Example of js initialization.

### ISSUE THREAD

**Issue by supersh86** [rafa8626/openplayer#23]
Good afternoon, I decided to test your player.
Tell me what data to insert into the
var player = new OpenPlayer ('player ID', [ads URL], [fullscreen effect], [HLS / Dash player options]);

Can you give an example?

**Comment by supersh86** [comment]
I'm use 
`<video id="hlsvideo" class="om-player__media" controls playsinline>
   <source src="https..." type="application/x-mpegURL">
</video>`

`var player = new OpenPlayer('hlsvideo', 'https...', true, {hls: {
          debug: true,
          capLevelToPlayerSize: true

        }
    }
        
);
`
And the player is not being initialized.
All links are working.

**Comment by rafa8626** [comment]
You need to add `player.init();` after your configuration

**Comment by supersh86** [comment]
!!!! thx!)))

**Comment by rafa8626** [comment]
You are welcome! And please give a star to this project if you can. I'd appreciate it a lot
