### ISSUE TITLE
Google Ima Autoplay 

### ISSUE THREAD

**Issue by supersh86** [rafa8626/openplayer#24]
Hello again
When IMA is initialized, the video starts to play.

**Comment by rafa8626** [comment]
That's the nature of the Ads; even examples in https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector perform autoplay, as well as YouTube and other media websites

**Comment by supersh86** [comment]
In this example, on startup
https://googleads.github.io/googleads-ima-html5/advanced/

**Comment by rafa8626** [comment]
In that example there’s no tag yet. Once you set the tag and click play it starts. In the player right now there’s no method to set the tag like that.

**Comment by supersh86** [comment]
Then it destroys the whole logic of using the player.
Because the player will always start automatically.

**Comment by rafa8626** [comment]
It depends of you user case scenario: as it is right now it mimics what YouTube does. If your purpose is different, let me know and I can re-evaluate how things are happening and I’ll try to work on it as soon as I can

**Comment by supersh86** [comment]
In my script, advertising starts after the player starts.
Especially Yutube happens for embedding without autostart.
https://www.youtube.com/embed/S_dfq9rFWAE

**Comment by rafa8626** [comment]
So, just to make sure what I would need to do: You will set the Ads URL like you did in the configuration of the player, but just don't want it to autoplay unless you click Play correct?

**Comment by rafa8626** [comment]
I think they way I could address that is by enabling `autoplay` attribute; so if it's present it will force the autoplay; otherwise, the user has to be the one clicking play to see the Ad

**Comment by supersh86** [comment]
All right, YouTube as well as many other players does the same.
If the video is embeddened to another site, it is launched only at the user's request.

Moreover, users can get negative experience if the video will be launched without his consent, and advertising agencies will be dissatisfied with the effectiveness.

**Comment by rafa8626** [comment]
I just pushed the fix for this; if you want the Ads to be autoplayed, you will need to indicate it setting `autoplay` attribute on the video tag; otherwise, it will launch when you click on the play button. Please download the master branch and let me know if it works for you. 

This won't be available through NPM until we set a new release (which will come soon).

**Comment by rafa8626** [comment]
Download it from https://github.com/rafa8626/openplayer/archive/master.zip

**Comment by supersh86** [comment]
Hi
If an error occurs:
` Ad error: AdError 303: No Ads VAST response after one or more Wrappers`
then run autoplay

**Comment by supersh86** [comment]
You can try it yourself.
https://anime.anidub.com/player/index222.php?vid=/bbb_sunflower_1080p_30fps_normal.mp4

**Comment by rafa8626** [comment]
No what i mean is an example of a VAST or page that can come with that error that you described above

**Comment by rafa8626** [comment]
Never mind I have another example. I’ll keep you posted if I have an update for this. Thanks

**Comment by rafa8626** [comment]
Please download the master file again. Let me know if that works for you (https://github.com/rafa8626/openplayer/archive/master.zip)

**Comment by supersh86** [comment]
Great Work!

**Comment by rafa8626** [comment]
Thanks for your help! Please let other people know about this player so they can star it and starts to gain more popularity please

**Comment by supersh86** [comment]
Write in the description that it supports Vpaid and VAST.

Your player can not be found for these queries, I accidentally stumbled across you through the page mediaelement

**Comment by rafa8626** [comment]
Thanks for the hint

**Comment by rafa8626** [comment]
Done. Added in the Topics area, the main description and the initial paragraph of the README file
